services:
  mercury:
    image: josiahdc/mercury:0.1
    ports:
      - "33333:33333"
    build:
      context: .
    networks:
      - ratatosk_ratatosk

networks:
  ratatosk_ratatosk:
    external: true