services:
  mercury:
    image: josiahdc/mercury:0.2
    ports:
      - "33333:33333"
    build:
      context: .
    networks:
      - ratatosk_ratatosk
    env_file:
      - mercury.env

networks:
  ratatosk_ratatosk:
    external: true